#url: https://y7kim.github.io
#baseurl: /agency-jekyll-theme/

# Site settings
title: María Virginia Bustos
email: mavirginia.bustos@gmail.com
description: "María Virginia Bustos' technical writing portfolio"

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin
    url: https://www.linkedin.com/in/mavirginiabustos/
  - title: github
    url: https://github.com/mavi-gh

# Build settings
markdown: kramdown
permalink: pretty
